logs:
    - syslog
    - kaa-node

syslog:
    source: /var/log/syslog 
    sink: debian.tric.kr:4321
    capacity: 10

kaa-node:
    source: /var/log/kaa/kaa-node.log 
    sink: debian.tric.kr:4322
    capacity: 10
